"""Initial migration

Revision ID: 0b4e2e8d4c80
Revises: 
Create Date: 2025-06-29 20:46:30.426373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4e2e8d4c80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('min_temp', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('max_temp', sa.Float(), nullable=False, server_default='100'))
        batch_op.drop_column('required_temp_range')

    op.execute("""
        UPDATE shipments
        SET name = 'shipment_' || id::text
        WHERE name IS NULL
    """)
    
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.alter_column('name', nullable=False)
        batch_op.create_unique_constraint('uq_shipments_name', ['name'])
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default="Owner"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_temp_range', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('max_temp')
        batch_op.drop_column('min_temp')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
