"""Added active column to alerts

Revision ID: b71ef691a6ab
Revises: 0b4e2e8d4c80
Create Date: 2025-07-15 12:56:05.752773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71ef691a6ab'
down_revision = '0b4e2e8d4c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
