"""Fixed weather data

Revision ID: ed79fd52cc7a
Revises: b71ef691a6ab
Create Date: 2025-07-20 02:53:28.862203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed79fd52cc7a'
down_revision = 'b71ef691a6ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizations')
    with op.batch_alter_table('weather_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_temp', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('external_temp', sa.Float(), nullable=True))
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('external_temp')
        batch_op.drop_column('internal_temp')

    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('join_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='organizations_pkey'),
    sa.UniqueConstraint('join_code', name='organizations_join_code_key'),
    sa.UniqueConstraint('name', name='organizations_name_key')
    )
    # ### end Alembic commands ###
