name: Publish Project Frontend to GHCR

on:
  push:
    # Only run this workflow if it is a commit to main.
    branches:
      - main
      - ci-cd
    tags:
      - 'v*'
    # Only run this workflow if the commit has modified files from backend
    paths:
      - epiready-backend/**

env:
  IMAGE_NAME: epiready-backend

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    defaults:
      run:
        working-directory: epiready-backend

    steps:
      - uses: actions/checkout@v2

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push to Docker Hub
        run: |
          docker tag epiready-frontend:latest ${{ secrets.DOCKER_USERNAME }}/epiready-frontend:latest
          docker tag epiready-frontend:latest ${{ secrets.DOCKER_USERNAME }}/epiready-frontend:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/epiready-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/epiready-frontend:${{ env.VERSION }}
          docker images