name: Build and deploy to Docker Hub
on:
  workflow_run:
    workflows: ["Publish Project Backend to Dockerhub", "Publish Project Frontend to Dockerhub"]
    types:
      - completed
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GIT_TAG: ${{ github.ref_name }}
    steps:
    - name: SSH into VM and deploy
      uses: appleboy/ssh-action@v1
      with:
        host: "15.222.16.78"
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        envs: GIT_TAG
        script: |
          cd epiready
          git checkout main
          git pull origin
          TAG_NO_V=${GIT_TAG#v}
          export TAG_NO_V
          echo "Deploying version: $TAG_NO_V"
          git checkout $GIT_TAG || true
          docker compose pull
          docker compose up -d