name: Build and deploy to Docker Hub
on:
  push:
    branches:
      - feat/ci-cd
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Docker compose build
        env:
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            VITE_MAPS_KEY: ${{ secrets.VITE_MAPS_KEY }}
            VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
            FRONTEND_ORIGINS: ${{ secrets.FRONTEND_ORIGINS }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
        run: |
          docker compose build
          docker compose up


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push to Docker Hub
        run: |
          docker tag epiready-frontend:latest ${{ secrets.DOCKER_USERNAME }}/epiready-frontend:latest
          docker tag epiready-backend:latest ${{ secrets.DOCKER_USERNAME }}/epiready-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/epiready-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/epiready-backend:latest
          docker images