name: Frontend Lint and Test

on:
  push:
    paths:
      - 'epiready-frontend/**'
  pull_request:
    paths:
      - 'epiready-backend/**'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./epiready-frontend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Build Frontend
        run: npm run build
      - name: Start Frontend Server
        run: npm run preview &
      - name: Check frontend
        run: curl --request GET http://localhost:4173/ --fail